nelmio_api_doc:
  documentation:
    info:
      title: "My API"
      description: "API documentation"
      version: "1.0.0"
  areas:
    path_patterns: # Adjust this according to your API routes
      - ^/api
