<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxRSGhg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxRSGhg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxRSGhg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxRSGhg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxRSGhg\App_KernelDevDebugContainer([
    'container.build_hash' => 'SxRSGhg',
    'container.build_id' => '9f0a6bef',
    'container.build_time' => 1741179730,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxRSGhg');
