<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLmU8AWx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLmU8AWx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLmU8AWx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLmU8AWx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLmU8AWx\App_KernelDevDebugContainer([
    'container.build_hash' => 'LmU8AWx',
    'container.build_id' => 'aaaaeb19',
    'container.build_time' => 1741100292,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLmU8AWx');
